Add pundit
aborov/industrial-auth-1 pull request #2
Opened 2024-07-18 12:17 UTC by aborov

2024-07-18 17:13 UTC, jniewiel requested changes
Hello Aleksei, great job overall with Pundit and creating your policies and controllers! However, there were a couple errors and things missing on some files. Please look through my comments for reference, and let me know when you make these changes. Thank you!

2024-07-18 17:13 UTC, jniewiel commented on app/policies/photo_policy.rb
> +  end
When I try to update one of my own photos, it throws an undefined variable NameError. 

Hint: Compare these variables with the ones you initialized at the start of this file.

2024-07-18 17:13 UTC, jniewiel commented on app/policies/photo_policy.rb
> +  end
Same issue here. When I try to delete one of my own photos, it throws an undefined variable NameError. 

Hint: The solution is the same as for the "def update?" issue.

2024-07-18 17:13 UTC, jniewiel commented on app/controllers/comments_controller.rb
> +  before_action :authorize_comment, only: [:edit, :update, :destroy]
Nice job implementing your authorizations for your comments!

2024-07-18 17:13 UTC, jniewiel commented on app/controllers/application_controller.rb
> +  after_action :verify_authorized, unless: :devise_controller?
Remember to also implement `after_action :verify_policy_scoped, only: :index, unless: :devise_controller?` in your application_controller!

2024-07-18 20:34 UTC, aborov commented on app/policies/user_policy.rb
> +  end
Thanks for feedback! This is solved now.

2024-07-18 20:34 UTC, aborov commented on app/policies/photo_policy.rb
> +  end
Thanks for feedback! This is solved now.

2024-07-18 20:34 UTC, aborov commented on app/policies/photo_policy.rb
> +  end
Thanks for feedback! This is solved now.

2024-07-18 20:46 UTC, jniewiel approved these changes
Great job with the requested changes, Aleksei!

2024-07-22 01:54 UTC, ajmompr requested changes
see comments; good start!

2024-07-22 01:54 UTC, ajmompr commented on app/controllers/application_controller.rb
> +  after_action :verify_authorized, unless: :devise_controller?
+1 Please refactor with @jniewiel's suggestion

2024-07-22 01:54 UTC, ajmompr commented on app/controllers/comments_controller.rb
> +  # def is_an_authorized_user
remove unnecessary/commented out code

2024-07-22 01:54 UTC, ajmompr commented on app/controllers/comments_controller.rb
Good job adding authorization to your comments controller. We can refactor the controller to add "before_action { authorize @comment || Comment}." This eliminates the need to add "authorize @comment" to the required actions

2024-07-22 01:54 UTC, ajmompr commented on app/controllers/follow_requests_controller.rb
> +  before_action :authorize_follow_request, only: [:accept, :destroy]
Good job; however, can be refactored to be more DRY. See my note on your comments controller note

2024-07-22 01:54 UTC, ajmompr commented on app/controllers/photos_controller.rb
> +    # @photo = Photo.find(params.fetch("id"))
remove unnecessary/commented out code

2024-07-22 01:54 UTC, ajmompr commented on app/controllers/photos_controller.rb
Good job; however, can be refactored to be more DRY. See my note on your comments controller note

2024-07-22 01:54 UTC, ajmompr commented on app/controllers/photos_controller.rb
> +  before_action :authorize_photo, only: [:show, :edit, :update, :destroy]
can be refactored to be more dry

2024-07-22 01:54 UTC, ajmompr commented on app/controllers/photos_controller.rb
> +    # end
remove commented out code

2024-07-22 01:54 UTC, ajmompr commented on app/controllers/photos_controller.rb
> +  # def ensure_user_is_authorized
the commented out code can also work! Instead of a redirect, you should use pundit not authorized error

2024-07-22 01:54 UTC, ajmompr commented on app/controllers/users_controller.rb
can be refactored to be more DRY; see notes on comments controller

2024-07-22 01:54 UTC, ajmompr commented on app/controllers/users_controller.rb
> +  def index
This page can be simplified down! Adding all of these actions are unnecessary. Adding before_action { authorize @user || User } will add User Policy

2024-07-22 01:54 UTC, ajmompr commented on app/policies/application_policy.rb
> +  attr_reader :user, :record
good job using pundit generator

2024-07-22 01:54 UTC, ajmompr commented on app/policies/comment_policy.rb
> +    user == record.author
can use inheritance here. can be made more dry ```ruby
def destroy? 
update?
end
```

2024-07-22 01:54 UTC, ajmompr commented on app/policies/comment_policy.rb
> +  class Scope < Scope
adding scope is unnecessary here. should inherit from application controller

2024-07-22 01:54 UTC, ajmompr commented on app/policies/follow_request_policy.rb
> +    user != record.recipient
should be "true"

2024-07-22 01:54 UTC, ajmompr commented on app/policies/follow_request_policy.rb
> +  class Scope < Scope
scope can be inherited from app policy

2024-07-22 01:54 UTC, ajmompr commented on app/policies/photo_policy.rb
> +    @photo.owner == user || !@photo.owner.private? || @photo.owner.followers.include?(user)
photo.owner... drop the @

2024-07-22 01:54 UTC, ajmompr commented on app/policies/photo_policy.rb
> +    @photo.owner == user
photo.owner... drop the @

2024-07-22 01:54 UTC, ajmompr commented on app/policies/photo_policy.rb
> +    @photo.owner == user
can be more DRY ;inheritance

2024-07-22 01:54 UTC, ajmompr commented on app/policies/user_policy.rb
> +    true
can be more DRY

2024-07-22 01:54 UTC, ajmompr commented on app/policies/user_policy.rb
> +    user == record
can be more DRY

2024-07-22 01:54 UTC, ajmompr commented on app/policies/user_policy.rb
> +    true
Can be more DRY

2024-07-22 01:54 UTC, ajmompr commented on app/views/users/liked.html.erb
see assignment notes in canvas. No need to add pundit to likes

2024-07-22 13:39 UTC, aborov commented on app/controllers/comments_controller.rb
> +  # def is_an_authorized_user
done

2024-07-22 14:03 UTC, aborov commented on app/controllers/comments_controller.rb
Thanks for suggestion! It's done now.

2024-07-22 16:22 UTC, aborov commented on app/controllers/photos_controller.rb
> +    # end
done

2024-07-22 23:28 UTC, aborov commented on app/controllers/application_controller.rb
> +  after_action :verify_authorized, unless: :devise_controller?
done!

2024-07-23 00:16 UTC, aborov commented on app/controllers/follow_requests_controller.rb
> +  before_action :authorize_follow_request, only: [:accept, :destroy]
done!

2024-07-23 00:17 UTC, aborov commented on app/controllers/photos_controller.rb
> +    # @photo = Photo.find(params.fetch("id"))
done

2024-07-23 00:18 UTC, aborov commented on app/controllers/photos_controller.rb
done

2024-07-23 00:18 UTC, aborov commented on app/controllers/photos_controller.rb
> +  before_action :authorize_photo, only: [:show, :edit, :update, :destroy]
done

2024-07-23 00:33 UTC, aborov commented on app/controllers/photos_controller.rb
> +  # def ensure_user_is_authorized
done

2024-07-23 00:35 UTC, aborov commented on app/controllers/users_controller.rb
> +  def index
done

2024-07-23 00:35 UTC, aborov commented on app/controllers/users_controller.rb
done

2024-07-23 00:37 UTC, aborov commented on app/policies/comment_policy.rb
> +    user == record.author
done

2024-07-23 00:37 UTC, aborov commented on app/policies/comment_policy.rb
> +  class Scope < Scope
done

2024-07-23 00:38 UTC, aborov commented on app/policies/follow_request_policy.rb
> +    user != record.recipient
fixed

2024-07-23 00:38 UTC, aborov commented on app/policies/follow_request_policy.rb
> +  class Scope < Scope
done

2024-07-23 00:39 UTC, aborov commented on app/policies/photo_policy.rb
> +    @photo.owner == user || !@photo.owner.private? || @photo.owner.followers.include?(user)
done

2024-07-23 00:39 UTC, aborov commented on app/policies/photo_policy.rb
> +    @photo.owner == user
done

2024-07-23 00:39 UTC, aborov commented on app/policies/photo_policy.rb
> +    @photo.owner == user
done

2024-07-23 00:40 UTC, aborov commented on app/policies/user_policy.rb
> +    user == record
done

2024-07-23 00:45 UTC, aborov commented on app/views/users/liked.html.erb
ok, reversed to original

2024-07-23 17:17 UTC, ajmompr approved these changes

2024-07-23 19:57 UTC, merged